[package]
name = "tb"
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
argh.workspace = true
tempdir = "0.3.7"
figment.workspace = true
serde.workspace = true
semver.workspace = true
libloading = "0.8.4"
log.workspace = true
env_logger.workspace = true
fs_extra = "1.3.0"
makemake = "0.1.3"
toml = "0.8.14"
