[package]
name = "data_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calyx = { path = "../../calyx"}
serde_json = "1.0.79"
rand = "0.8.4"
argh = "0.1"
serde = "1.0.137"
lazy_static = "1.4.0"
