[package]
name = "gen_json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calyx = { path = "/Users/calebkim/learning/calyx/calyx"}
serde_json = "1.0.79"
argh = "0.1"
serde = "1.0.137"
lazy_static = "1.4.0"
