[package]
name = "calyx"
version = "0.1.0"
authors = [ "The FuTIL Team" ]
edition = "2018"
build = false
# build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
petgraph = "0.5.0"
bumpalo = "3.2.1"
atty = "0.2.14"
derivative = "2.1.1"
pest = "2.1.3"
pest_derive = "2.1.0"
pest_consume = "1.0.6"
itertools = "0.9.0"
lazy_static = "1.4.0"
vast = { git = "https://github.com/vegaluisjose/vast.git", branch = 'main' }
boolean_expression = "0.4.1"

[dependencies.pretty]
version = "0.9.0"
features = ["termcolor"]
