[package]
name = "calyx"
version = "0.1.0"
authors = [
  "Samuel Thomas <sgt43@cornell.edu>",
  "Kenneth Fang <kwf37@cornell.edu>",
  "Zhijing Li <zl679@cornell.edu>",
  "Rachit Nigam <rnigam@cs.cornell.edu>",
  "Adrian Sampson <asampson@cs.cornell.edu>",
]
edition = "2018"
build = false
# build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
structopt = "~0.3"
quickcheck = "0.9.0"
petgraph = "~0.5"
better-panic = "~0.2"
sexpy = "0.5.3"
itertools = "~0.9"
bumpalo = "3.2.0"
atty = "~0.2"

[dependencies.pretty]
version = "~0.9"
features = ["termcolor"]

# [build-dependencies]
# clap = "2.33"
# structopt = "~0.3"
