[package]
name = "cider-data-converter"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cider.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
itertools = { workspace = true }
argh.workspace = true
thiserror.workspace = true
nom = "7.1"

num-bigint = { version = "0.4" }
num-rational = { version = "0.4" }
num-traits = { version = "0.2" }

[dev-dependencies]
proptest = "1.0.0"
