[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "synthrep"
authors = [{ name = "The Calyx Authors" }]
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = ["pandas", "plotly"]
readme = "README.md"

[project.scripts]
synthrep = "synthrep.cli:main"
