[package]
name = "fsm_to_dot"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh.workspace = true
petgraph.workspace = true

calyx-ir.workspace = true
calyx-utils.workspace = true
calyx-frontend.workspace = true
calyx-opt.workspace = true
