[package]
name = "yxi"
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
homepage.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
argh.workspace = true
serde_json = "1.0.79"

calyx-utils = { path = "../../calyx-utils" }
calyx-frontend = { path = "../../calyx-frontend" }
calyx-opt = { path = "../../calyx-opt" }

[dependencies.calyx-ir]
path = "../../calyx-ir"
features = ["serialize"]
