[package]
name = "calyx-pass"
default-run = "calyx-pass"
version = "0.2.1"
edition.workspace = true

[[bin]]
name = "calyx-pass"
path = "src/main.rs"

[dependencies]
argh = "0.1.12"
crossterm = "0.27.0"
similar = "2.5.0"
tempdir = "0.3.7"
