name: fud2 tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [docker, hash]
    container: ghcr.io/calyxir/calyx:${{ needs.hash.outputs.hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install --path fud2
      - run: cargo test -p fud
      - run: runt fud2/tests/runt -d -o fail
